# MetaData
sonar.organization=base-td
sonar.projectKey=base-td_sec_congerapp_1_front

sonar.projectVersion=1.0.0
sonar.projectEncoding=UTF-8

# Language and tools
sonar.language=js

# Source
sonar.sources=src

# Quality Gate
sonar.qualitygate.wait=false