name: SECU

on:
  push:
    branches:
      - main

jobs:
  # SonarQube:
  #   uses: ./.github/workflows/1_sonarqube.yml
  #   secrets: inherit

  # Snyk

  Build_Docker:
    # needs: [SonarQube]
    uses: ./.github/workflows/2_docker.yml
    secrets: inherit

  # TrivyScan:
  #   # needs: [Build_Docker]
  #   uses: ./.github/workflows/3_trivy.yml
  #   secrets: inherit

  OwaspZap:
    needs: [Build_Docker]
    uses: ./.github/workflows/4_owaspzap.yml
    secrets: inherit
    permissions:
      issues: write